# Cloudflare Workers設定ファイル
name = "lecture-to-text-worker"
main = "src/worker.js"
compatibility_date = "2025-09-13"

[env.production]
name = "lecture-to-text-worker"

[env.production.vars]
CLOUD_RUN_API_URL = "https://lecture-to-text-api-1088729528504.asia-northeast1.run.app"
VERCEL_URL = "https://lecture-to-text-hnc481qt0-yoshis-projects-421cbceb.vercel.app"

# ルート設定
[[routes]]
pattern = "lecture-to-text.com/*"
zone_name = "lecture-to-text.com"

[[routes]]
pattern = "www.lecture-to-text.com/*"
zone_name = "lecture-to-text.com"
