name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]
    paths:
      - 'cloud_run_api.py'
      - 'requirements.txt'
      - 'Dockerfile'
      - 'text_enhancer.py'
      - 'config.py'
      - 'deploy-cloud-run.sh'
  workflow_dispatch:

env:
  PROJECT_ID: lecture-to-text-472009
  SERVICE_NAME: lecture-to-text-api
  REGION: asia-northeast1

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}

    - name: Configure Docker for GCR
      run: gcloud auth configure-docker

    - name: Verify authentication
      run: |
        echo "Verifying Google Cloud authentication..."
        gcloud auth list
        gcloud config get-value project

    - name: Build and push Docker image
      run: |
        echo "Building Docker image..."
        docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }} .
        echo "Pushing Docker image to GCR..."
        docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
        echo "Docker image pushed successfully"

    - name: Deploy to Cloud Run
      run: |
        echo "Deploying to Cloud Run..."
        gcloud run deploy ${{ env.SERVICE_NAME }} \
          --image gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }} \
          --platform managed \
          --region ${{ env.REGION }} \
          --memory 16Gi \
          --cpu 4 \
          --max-instances 10 \
          --allow-unauthenticated
        echo "Cloud Run deployment completed successfully"
